package cl.tchile.app.helper;

import org.json.JSONObject;
import org.json.XML;
import org.springframework.stereotype.Component;

import com.google.gson.Gson;
import com.response.accpspwi.accpspws.ProgramInterface;
import com.response.accpspwi.accpspws.ProgramInterface.AccpspwoSalida;
import com.response.accpspwi.accpspws.ProgramInterface.AccpspwoSalida.AccpspwoOLineas;
import com.response.accpspwi.accpspws.ProgramInterface.AccpspwoSalida.AccpspwoOLineas.AccpspwoPsLineas;

import cl.tchile.app.vo.ConsultaPSPrincipalesLineasVO;

/**
 * The Class ConsultaPSPrincipalesLineasHerlper.
 */
@Component
public class ConsultaPSPrincipalesLineasHerlper {

	/**
	 * Sets the response consulta PS principales lineas.
	 *
	 * @return the program interface
	 */
	public ProgramInterface setResponseConsultaPSPrincipalesLineas() {
//		String respuestaDummy ="";
		String respuestaDummy = "<resp:accpspwo_o_cod_error>0</resp:accpspwo_o_cod_error>\r\n"
				+ "            <resp:accpspwo_o_desc_error>PROCESO EXITOSO</resp:accpspwo_o_desc_error>\r\n"
				+ "            <resp:accpspwo_o_programa>ACCPSPWS</resp:accpspwo_o_programa>\r\n"
				+ "            <resp:accpspwo_o_cod_db>0</resp:accpspwo_o_cod_db>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_o_area>002</resp:accpspwo_o_area>\r\n"
				+ "               <resp:accpspwo_o_fono>32991312</resp:accpspwo_o_fono>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>5825</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_desc>PLAN MIN ILIMITADO LOC HOGAR</resp:accpspwo_o_desc>\r\n"
				+ "                  <resp:accpspwo_o_cod_fam>00004</resp:accpspwo_o_cod_fam>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>40701</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>7447</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_desc>PLAN PRO2 IPTV OPEN</resp:accpspwo_o_desc>\r\n"
				+ "                  <resp:accpspwo_o_cod_fam>00007</resp:accpspwo_o_cod_fam>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>70702</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>7394</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_desc>PLAN FO 600/600 MB MIGRACION</resp:accpspwo_o_desc>\r\n"
				+ "                  <resp:accpspwo_o_cod_fam>00002</resp:accpspwo_o_cod_fam>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>20401</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "            <resp:accpspwo_o_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "               <resp:accpspwo_ps_lineas>\r\n"
				+ "                  <resp:accpspwo_o_ps>0</resp:accpspwo_o_ps>\r\n"
				+ "                  <resp:accpspwo_o_subgr2>0</resp:accpspwo_o_subgr2>\r\n"
				+ "               </resp:accpspwo_ps_lineas>\r\n"
				+ "            </resp:accpspwo_o_lineas>\r\n"
				+ "";
		
		
		respuestaDummy = respuestaDummy.replace("resp:", "");
		JSONObject soapDatainJsonObject = XML.toJSONObject(respuestaDummy);
		ConsultaPSPrincipalesLineasVO respuestaBd = new Gson().fromJson(soapDatainJsonObject.toString(), ConsultaPSPrincipalesLineasVO.class);
		
		ProgramInterface response = new ProgramInterface();
		AccpspwoSalida camposSalida = new AccpspwoSalida();
		
		camposSalida.setAccpspwoOCodError(respuestaBd.getAccpspwo_o_cod_error());
		camposSalida.setAccpspwoODescError(respuestaBd.getAccpspwo_o_desc_error());
		camposSalida.setAccpspwoOPrograma(respuestaBd.getAccpspwo_o_programa());
		camposSalida.setAccpspwoOCodDb(respuestaBd.getAccpspwo_o_cod_db());
		AccpspwoOLineas lineas = null;
		
		for (cl.tchile.app.vo.ConsultaPSPrincipalesLineasVO.AccpspwoOLineas lineaBd : respuestaBd.getAccpspwo_o_lineas()) {
				lineas = new AccpspwoOLineas();
				if(null != lineaBd.getAccpspwo_o_area()) {
					lineas.setAccpspwoOArea(lineaBd.getAccpspwo_o_area());
				}
				if(null != lineaBd.getAccpspwo_o_fono()) {
					lineas.setAccpspwoOFono(lineaBd.getAccpspwo_o_fono());
				}

				AccpspwoPsLineas psLinea = null;
				for (cl.tchile.app.vo.ConsultaPSPrincipalesLineasVO.AccpspwoOLineas.AccpspwoPsLineas psLineaBd : lineaBd.getAccpspwo_ps_lineas()) {
					psLinea = new AccpspwoPsLineas();
					if(null != psLineaBd.getAccpspwo_o_ps()) {
						psLinea.setAccpspwoOPs(psLineaBd.getAccpspwo_o_ps());
					}
					if(null != psLineaBd.getAccpspwo_o_desc()) {
						psLinea.setAccpspwoODesc(psLineaBd.getAccpspwo_o_desc());
					}
					if(null != psLineaBd.getAccpspwo_o_cod_fam()) {
						psLinea.setAccpspwoOCodFam(psLineaBd.getAccpspwo_o_cod_fam());
					}
					if(null != psLineaBd.getAccpspwo_o_subgr2()) {
						psLinea.setAccpspwoOSubgr2(psLineaBd.getAccpspwo_o_subgr2());
					}					
					lineas.getAccpspwoPsLineas().add(psLinea);
				}
				
				camposSalida.getAccpspwoOLineas().add(lineas);
		}
//		
		response.setAccpspwoSalida(camposSalida);
		return response;
	}
}
